"""Add BSI catalog tables (Block 18).

Revision ID: 0003_bsi_catalog_tables
Revises: 0002_extraction_fields
Create Date: 2026-01-17 00:00:00.000000

Diese Migration erstellt die Tabellen ``bsi_catalogs``, ``bsi_modules`` und
``bsi_requirements`` für den Upload und die Persistenz von BSI‑Katalogen.
Sie referenziert als Vorgänger die Revision ``0002_extraction_fields``. In
Block 17 hatten wir die Revision ``0002_extraction_fields`` definiert, um
Extraktionsspalten zu den Quellen hinzuzufügen. Hier verwenden wir den
kürzeren Revision‑Bezeichner, damit die ``alembic_version``‑Tabelle (32
Zeichen) keine Probleme verursacht. Ohne diesen Fix konnte Alembic die
Revision nicht auflösen, da der in der ursprünglichen Datei verwendete
Bezeichner ``0002_add_extraction_fields_to_sources`` zu lang ist.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0003_bsi_catalog_tables'
down_revision = '0002_extraction_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bsi_catalogs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=512), nullable=False),
        sa.Column('storage_path', sa.String(length=1024), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'bsi_modules',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('catalog_id', sa.String(length=36), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['catalog_id'], ['bsi_catalogs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'bsi_requirements',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('module_id', sa.String(length=36), nullable=False),
        sa.Column('req_id', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['bsi_modules.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bsi_requirements')
    op.drop_table('bsi_modules')
    op.drop_table('bsi_catalogs')
    # ### end Alembic commands ###